version: "3"
services:
  orv:
    build: ./orv
    ports:
      - "3000:80"

  app:
    build: .
    ports:
      - "3000:3000"
      - "1883:1883"

    env_file:
      - .env
    volumes:
      - .:/app

    # depends_on:
    #   - orv
