FROM pytorch/pytorch:2.2.2-cuda11.8-cudnn8-runtime

WORKDIR /app

RUN apt-get update && apt-get install -y \
    libgl1-mesa-glx \
    libglib2.0-0 \

COPY . /app

RUN pip install --no-cache-dir \
    opencv-python \
    torchvision \
    requests \
    Pillow

RUN mkdir -p /app/model

CMD ["python", "main.py"]
